### ISSUE TITLE
Toggling a shader fails with....a  lot of errors

### ISSUE THREAD

**Issue by kaii-lb** [loqusion/hyprshade#1]
As stated in the title, toggling a shader doesn't work and fails with a wall of text. Turning them off or on manually however, works perfectly fine (aka hyprshade on shader | hyprshade off).

Here's the output: https://pastebin.com/p66E7Uyq

I tried every possible way to build/install hyprshade so its not a version issue

**Comment by loqusion** [comment]
`hyprshade toggle` currently requires you to have a config file, which is a mistake on my part — it shouldn't be needed if you provide an argument. I should also make the error message more concise.

**Comment by loqusion** [comment]
Should be fixed in [v0.8.1](https://github.com/loqusion/hyprshade/tree/v0.8.1) -- try the package from PyPI or `hyprshade-git` on the aur.

**Comment by kaii-lb** [comment]
> I should also make the error message more concise

i thought that it couldn't find the config **directory** which is why i was so confused.

But now it seems theres another issue, the new hyprland release (v0.28) changed how hyprctl -j works. It now adds `adding <command>` infront of the json output which breaks jq it seems. i'll submit a hacky-ass change that fixes it in a bit.

**Comment by loqusion** [comment]
Fixed by d0aebc6.
