### ISSUE TITLE
Hyprshade install config no found ?

### ISSUE THREAD

**Issue by Sytxx** [loqusion/hyprshade#15]
How can i fix this, when i exec hyprshade install and its show me error : Config File not found.

![image](https://github.com/loqusion/hyprshade/assets/56584493/5e130571-1d2d-4db5-b76a-9171a66ef938)

Os : Endeavor OS
Kernel : 6.6.7-arch1-1

**Comment by loqusion** [comment]
`hyprshade install` requires a config file; see https://github.com/loqusion/hyprshade#scheduling.
