### ISSUE TITLE
AUR installation fails with `hyprland exists in filesytem`

### ISSUE THREAD

**Issue by stickyburn** [loqusion/hyprshade#16]
Installing hyprshade with `yay` fails with:

```
(13/13) checking for file conflicts                                      [#########################################] 100%
error: failed to commit transaction (conflicting files)
hyprland: /usr/bin/Hyprland exists in filesystem
hyprland: /usr/bin/hyprctl exists in filesystem
hyprland: /usr/lib/libwlroots.so.13032 exists in filesystem
hyprland: /usr/share/wayland-sessions exists in filesystem
```

I just reinstalled Hyprland but built it manually. Could that be linked?

Thanks! :heart:

**Comment by loqusion** [comment]
Hyprland is listed as a dependency in the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyprshade). To mark it as manually installed run something like:

```sh
sudo pacman -D --asexplicit <pkgs>
```

as per [this stackoverflow post](https://unix.stackexchange.com/questions/1993/make-package-explicitly-installed-in-pacman).

Then installing `hyprshade` should work.

**Comment by loqusion** [comment]
`hyprland` is marked as a dependency in `hyprshade`'s PKGBUILD. There might be some way to mark `hyprland` as installed without actually installing it with `pacman`, but I'm unaware of it.

To save headache, I'd recommend installing `hyprland` with [`makepkg -i`](https://wiki.archlinux.org/title/Makepkg) to have it registered in `pacman`'s database.

**Comment by stickyburn** [comment]
Can I pass flags like no-systemd with makepkg?

**Comment by loqusion** [comment]
Idk

**Comment by loqusion** [comment]
Oh btw commands like `hyprshade install` which activate shaders on schedule do depend on systemd atm
