### ISSUE TITLE
[Bug] Shader doesn't apply to cursor

### ISSUE THREAD

**Issue by vanillacode314** [loqusion/hyprshade#31]
The shaders apply to my whole screen except the cursor, I would attach a screenshot but not sure how to take one with a cursor in it.

Thanks for this awesome piece of software, would love if this issue could be resolved :)

**Comment by loqusion** [comment]
This is an issue with Hyprland, not Hyprshade.

**Comment by sina-salahshour** [comment]
> This is an issue with Hyprland, not Hyprshade.

is there a workaround for this problem?

**Comment by username391** [comment]
Is there any workaround?
