### ISSUE TITLE
Multi-monitor support?

### ISSUE THREAD

**Issue by codelif** [loqusion/hyprshade#32]
Is it possible to configure different shaders for different monitors?

**Comment by loqusion** [comment]
Hyprshade is essentially a wrapper around Hyprland's `decoration:screen_shader` feature, which currently doesn't support that degree of granularity. AFAIK this would have to be supported upstream.

**Comment by Hanssen0** [comment]
For anyone interested in applying a shader with a multi-monitor setup:
Though `decoration:screen_shader` doesn't support monitor-based setup, we can still check the monitor ID in the shader by `uniform int wl_output;`

https://github.com/hyprwm/Hyprland/blob/4e785d12a91117cd5b255052799d1a051d9976c0/src/render/OpenGL.cpp#L1246

It is possible to apply different effects on different displays by branching the shader workflow.

Example:
https://github.com/Hanssen0/dotfiles/blob/74fd8b89e52417b7a978c429d5fb4947c67edc47/hypr/shaders/vibrance.glsl#L19-L22
