### ISSUE TITLE
Correct example

### ISSUE THREAD

**Issue by thangisme** [loqusion/hyprshade#36]
In your example file, the section config is `[[shaders]]`. However `[[shades]]` should be the right one. Also I cant get the temperature config to work with blue light filter whether it's `[shades.config]` or `[shaders.config]`
```
[[shades]]
name = "blue-light-filter"
start_time = 19:00:00
end_time = 06:00:00
[shades.config]
temperature = 3400
```

**Comment by loqusion** [comment]
`shaders` and `shaders.config` are features which will be soon introduced in the `4.0.0` release. They are present in the [`examples/config.toml` on `main` branch](https://github.com/loqusion/hyprshade/blob/docs/readme-4.0.0/examples/config.toml) due a simplification of this project's repository organization: all development is done on the `main` branch, and stable versions are pinned with tags (e.g. [`3.2.1`](https://github.com/loqusion/hyprshade/blob/3.2.1/examples/config.toml)) and [released via PyPI](https://pypi.org/project/hyprshade/#history). The only exception to this is that updates to the README are kept on separate branches (e.g. [`docs/readme-4.0.0`](https://github.com/loqusion/hyprshade/tree/docs/readme-4.0.0)) to avoid advertising features not present in any stable version.

If you want to use `shaders.config`, you can use an unstable version of `hyprshade`. Right now, the only officially supported way to do this is to use the [`hyprshade-git` AUR package](https://aur.archlinux.org/packages/hyprshade-git).
