### ISSUE TITLE
How to use shaders from shaders folder?

### ISSUE THREAD

**Issue by mylinuxforwork** [loqusion/hyprshade#37]
Hi,
I have found more shaders in the folder https://github.com/loqusion/hyprshade/tree/main/shaders
But only invert-colors is working in addition the default shaders.

How can I use the other shaders with mustache ending?

Get the following error message when try using them:
unexpected has token on line 17 

Thanks...

**Comment by loqusion** [comment]
Please see the newly-added [FAQ section](https://github.com/loqusion/hyprshade?tab=readme-ov-file#i-tried-to-copy-something-from-the-examples-or-shaders-directory-but-its-not-working-what-gives) on the README.

**Comment by mylinuxforwork** [comment]
Thanks for your feedback.
