### ISSUE TITLE
Screenshots - Discussion

### ISSUE THREAD

**Issue by loqusion** [loqusion/hyprshade#4]
It would be nice if the README had screenshots of shaders for demonstration purposes. However, I ([and others](https://github.com/hyprwm/Hyprland/issues/1140#issuecomment-1614863627)) have not been able to take proper screenshots (a screenshot is taken without the shader applied).

EDIT: Ok, screenshots with shaders are working again. I'll upload them soon.

**Comment by mekb-turtle** [comment]
how do you screenshot with the shaders? (using NVIDIA)

**Comment by loqusion** [comment]
@mekb-turtle Personally, I use [grimblast](https://github.com/hyprwm/contrib#grimblast). https://github.com/loqusion/dotfiles/blob/5fdc751adbe9862bf3309be8dd8b0eb2650c009e/.config/hypr/keybinds.conf#L29-L30

**Comment by mekb-turtle** [comment]
@loqusion I'm using my own script for grim, but it still doesn't show the shader, perhaps grimblast has its own thing to apply the shader?

**Comment by loqusion** [comment]
@mekb-turtle On my machine I can run `grim -g $(slurp) - | wl-copy` and it works just fine. Looks like you got NVIDIA'd.

**Comment by mekb-turtle** [comment]
ah yeah, it's probably my NVIDIA card. I might be buying an AMD card soon so hopefully it'll work on there
