### ISSUE TITLE
how to reduce the intensity of blue-light-filter

### ISSUE THREAD

**Issue by kaushiksahu18** [loqusion/hyprshade#40]
### How can i reduce the intensity of blue-light-filter

i have run this cmd
```sh
hyprshade on blue-light-filter
```

**Comment by loqusion** [comment]
This feature is coming soon in `v4.0.0`; see [the `4.0.0` readme](https://github.com/loqusion/hyprshade/tree/docs/readme-4.0.0?tab=readme-ov-file#shader-customization).

For now, you can copy [`blue-light-filter.glsl`](https://github.com/loqusion/hyprshade/blob/3.2.1/shaders/blue-light-filter.glsl) to `~/.config/hypr/shaders` and change [`temperatureStrength`](https://github.com/loqusion/hyprshade/blob/3.2.1/shaders/blue-light-filter.glsl#L8) to suit your preference.

**Comment by SilenceFox** [comment]
Sorry for reopening. If anyone stumbles here I made a [little helper](https://gist.github.com/SilenceFox/44dd65614af11aa8b12640e91128af66).

Thanks for the project, can't live without a blue light filter!

**Comment by loqusion** [comment]
@SilenceFox, there are some great ideas in your script! I'll definitely add them if I can after releasing 4.0.0, I decided to rewrite this project from scratch in Rust so it might take a while though.
