### ISSUE TITLE
Fedora Support ??

### ISSUE THREAD

**Issue by Enigma1309** [loqusion/hyprshade#43]
installed via pip since there's no official support

it always shows shader not found

i tried manually copying the shader from repo to `~/.config/hypr/ shaders/` directory it still shows error

```
❯ hyprshade auto
Error: Shader 'blue-light-filter' could not be found in any of the following directories:
	/home/user/.config/hypr/shaders
❯ ls ~/.config/hypr/shaders
 blue-light-filter.glsl.mustache
 color-filter.glsl.mustache
 grayscale.glsl.mustache
 invert-colors.glsl
 vibrance.glsl.mustache
```

i also tried to remove .mustache extension but then it seems to show error only invert-colors shader works (which is not something i plan to use)

**Comment by loqusion** [comment]
I couldn't reproduce this issue. I installed Hyprshade to a venv (my system doesn't permit global `pip` installs) and got:

```sh
./hyprshade-venv/bin/hyprshade ls -l
  bloom              /home/loqusion/.config/hypr/shaders
  blue-light-filter  /home/loqusion/hyprshade-venv/share/hyprshade/shaders
  blur               /home/loqusion/.config/hypr/shaders
  crt                /home/loqusion/.config/hypr/shaders
  drugs              /home/loqusion/.config/hypr/shaders
  vibrance           /home/loqusion/hyprshade-venv/share/hyprshade/shaders
```

Try [installing pipx](https://pipx.pypa.io/stable/) and then installing Hyprshade with `pipx install hyprshade`. Let me know if that works for you.

**Comment by loqusion** [comment]
Also, be sure to remove the shaders you manually copied to `~/.config/hypr/shaders`. Shaders with the `.mustache` extension are unsupported by the latest stable release.

**Comment by Enigma1309** [comment]
thanks for your fast response
removing the pip version and installing via pipx does actually seem to work but it doesn't ship with other shaders (like grayscale) 
it only shows vibrance and blue-light-filter is there any other way to use them?

**Comment by loqusion** [comment]
`blue-light-filter` and `vibrance` are the only shaders available in the latest stable release. The others will be added in the next release.

**Comment by Enigma1309** [comment]
okay thanks :+1:

**Comment by Enigma1309** [comment]
for those whose keybinds are not working add this line to your hyprland.conf

`env = PATH,$PATH:~/.local/bin/`

or give absolute path
`env = PATH,$PATH:/home/put_your_username_here/.local/bin/`

**Comment by loqusion** [comment]
Appending to `$PATH` in `hyprland.conf` tightly couples your `$PATH` definition to Hyprland, meaning you have to duplicate your work if you want it in any other context.

Here's how to add to `$PATH` based on the shell you're using:

- [`bash`](https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path)
- [`zsh`](https://stackoverflow.com/questions/11530090/adding-a-new-entry-to-the-path-variable-in-zsh)
- [`fish`](https://fishshell.com/docs/current/cmds/fish_add_path.html)
