### ISSUE TITLE
Error bar not going away after error is fixed in shader

### ISSUE THREAD

**Issue by LAZAR-code** [loqusion/hyprshade#46]
### About the Bug

**Describe the bug**
The error bar is not going away after i fix the error in the shader or use another shader.

**To reproduce**

1. Turn on a shader with an error
2. Fix the error
3. Error bar doesn't go away

**Expected behavior**
Error bar goes away

### Environment

- **Hyprland version**:

```text
Hyprland, built from branch main at commit 00c862686354d139a53222d41a1c80d698a50c43  (hyprctl: add submap request).
Date: Tue Sep 24 12:25:05 2024
Tag: v0.43.0-57-g00c86268, commits: 5253
built against aquamarine 0.4.1
```

- **Hyprshade version**:

```text
hyprshade, version 3.2.1
```

- **Installation method**: AUR
- **Linux distribution**: Arch (EndeavourOS)

- **Hyprshade config**:
Not using a config

**Comment by loqusion** [comment]
Yeah, it's annoying. You have to run `hyprctl reload` to get the error message to go away. Ideally it should just go away once the problem is fixed.

Anyway, this is a Hyprland issue, not something Hyprshade has any control over.

**Comment by LAZAR-code** [comment]
Thanks.
