### ISSUE TITLE
Shader problem

### ISSUE THREAD

**Issue by oyuncuGo1** [loqusion/hyprshade#49]
![1730373329_grim](https://github.com/user-attachments/assets/855f615b-dd11-41eb-b533-a3b446666046)
says this when ı run
hyprshade toggle /home/gorkem/Downloads/hyprshaders-main/orig.frag

**Comment by loqusion** [comment]
That's to be expected. As the error message says, using a shader with uniform 'time' requires `debug:damage_tracking` in your `hyprland.conf` to be switched off. Refer to the Hyprland wiki for instructions on how to do so.

**Comment by oyuncuGo1** [comment]
thank you
