### ISSUE TITLE
Example config typo `shaders` instead of `shades`

### ISSUE THREAD

**Issue by danimateo** [loqusion/hyprshade#50]
### About the Bug
The example config.toml file in the repo has `[[shaders]]` instead of `[[shades]]`, the one in the README is good, took me some time to figure out though :sweat_smile:

**Comment by loqusion** [comment]
See the [FAQ](https://github.com/loqusion/hyprshade?tab=readme-ov-file#i-tried-to-copy-something-from-the-examples-or-shaders-directory-but-its-not-working-what-gives).
