### ISSUE TITLE
Should have a flake for NixOS

### ISSUE THREAD

**Issue by knarkzel** [loqusion/hyprshade#6]
This way it's easy for NixOS users to use this.

**Comment by loqusion** [comment]
[PACKAGING.md](https://github.com/loqusion/hyprshade/blob/main/PACKAGING.md) might be helpful for anyone who wants to make packages for distributions besides Arch Linux

**Comment by donovanglover** [comment]
Looks like hyprshade is [now in nixos-unstable](https://search.nixos.org/packages?channel=unstable&query=hyprshade), so a flake isn't needed.

**Comment by loqusion** [comment]
Alright; in that case, I'll close the issue for now.
