### ISSUE TITLE
`hyprshade install` cannot create the systemd file itself

### ISSUE THREAD

**Issue by ph3n92h3** [loqusion/hyprshade#8]
After copying the configuration file according to the document, directly running `hyprshade install`  will return an error：
```
Error: [Errno 2] No such file or directory: '/home/<username>/.config/systemd/user/hyprshade.service'
```
`hyprshade install` can run successfully only after manually creating this systemd file.

OS: Arch Linux x86_64
Kernel: 6.5.1
hyprshade version: aur/hyprshade-git 0.10.0.r1.g7b78d98-1, however, this error has occurred in previous versions.

**Comment by loqusion** [comment]
ac56883 should fix it, can you try it from `hyprshade-git`?

**Comment by ph3n92h3** [comment]
Thank you, it works fine now!
